from __future__ import annotations

from .ir import (
    AutomatonSpec,
    ChannelSpec,
    ClassSpec,
    ClockSpec,
    ContractSpec,
    EnvSpec,
    LocationSpec,
    ObserverSpec,
    PhyContractModel,
    PropertySpec,
    Provenance,
    TransitionSpec,
    VariableSpec,
)

SOURCE = "PHY_level_formalization_reviewed-2026-06-06-143000.tex"


def p(section: str, line: int | None = None) -> Provenance:
    return Provenance(source=SOURCE, section=section, line=line)


def build_default_contract() -> PhyContractModel:
    classes = [
        ClassSpec("SINRClass", ["OUTAGE", "LOW", "OK", "HIGH"], p("alpha_PHY/X_disc", 170)),
        ClassSpec("BLERClass", ["OK", "HIGH", "CRITICAL"], p("alpha_PHY/X_disc", 193)),
        ClassSpec("CQIClass", ["GOOD", "LIMITED", "BAD"], p("alpha_PHY/X_disc", 194)),
        ClassSpec("IClass", ["OK", "HIGH", "CRITICAL"], p("alpha_PHY/X_disc", 195)),
        ClassSpec("DopplerClass", ["OK", "HIGH"], p("alpha_PHY/X_disc", 196)),
        ClassSpec("DelaySpreadClass", ["OK", "HIGH"], p("alpha_PHY/X_disc", 197)),
        ClassSpec("PowerClass", ["OK", "LOW", "ABSENT"], p("alpha_PHY/X_disc", 198)),
        ClassSpec("DRTClass", ["OK", "BAD"], p("alpha_PHY/X_disc", 199)),
        ClassSpec("PilotDensityClass", ["OK", "LOW", "FAILED"], p("alpha_PHY/X_disc", 200)),
        ClassSpec("PayloadSenseClass", ["OK", "LIMITED", "FAILED"], p("alpha_PHY/X_disc", 201)),
        ClassSpec("PRSClass", ["OK", "LIMITED", "FAILED"], p("alpha_PHY/X_disc", 202)),
        ClassSpec("BeamErrorClass", ["LOCKABLE", "UNSTABLE", "CRITICAL"], p("alpha_PHY/X_disc", 203)),
        ClassSpec("BlockageClass", ["NONE", "SUSPECTED", "CONFIRMED"], p("alpha_PHY/X_disc", 204)),
        ClassSpec("PdClass", ["OK", "LOW", "FAILED"], p("alpha_PHY/X_disc", 205)),
        ClassSpec("RfaClass", ["OK", "HIGH", "CRITICAL"], p("alpha_PHY/X_disc", 206)),
        ClassSpec("AccClass", ["OK", "LIMITED", "FAILED"], p("alpha_PHY/X_disc", 207)),
        ClassSpec("CRBClass", ["OK", "LOOSE", "UNUSABLE"], p("alpha_PHY/X_disc", 208)),
        ClassSpec("AoSClass", ["FRESH", "STALE", "EXPIRED"], p("alpha_PHY/X_disc", 209)),
        ClassSpec("CapClass", ["OK", "LIMITED", "FAILED"], p("alpha_PHY/X_disc", 210)),
        ClassSpec("CoverageClass", ["OK", "LIMITED", "FAILED"], p("alpha_PHY/X_disc", 211)),
        ClassSpec("ResourceShareClass", ["OK", "LIMITED", "STARVED"], p("alpha_PHY/X_disc", 212)),
        ClassSpec("MisClass", ["OK", "WARN", "CRITICAL"], p("alpha_PHY/X_disc", 213)),
        ClassSpec("BMOverheadClass", ["OK", "HIGH", "EXCESSIVE"], p("alpha_PHY/X_disc", 214)),
        ClassSpec(
            "ChannelClass",
            ["NOMINAL", "INTERFERENCE_LIMITED", "MOBILITY_LIMITED", "MULTIPATH_LIMITED", "BLOCKAGE", "OUTAGE"],
            p("alpha_PHY/X_disc", 215),
        ),
        ClassSpec(
            "SignalClass",
            ["NOMINAL", "PILOT_BASED", "PAYLOAD_ASSISTED", "RECONFIGURING", "LIMITED"],
            p("alpha_PHY/X_disc", 217),
        ),
        ClassSpec(
            "BeamClass",
            ["SEARCH", "TRACK", "LOCKED", "PREDICT", "MISALIGNED", "RECOVERING", "HO_ASSIST", "FAILED"],
            p("alpha_PHY/X_disc", 219),
        ),
        ClassSpec(
            "SensingState",
            [
                "SensingQoSOk",
                "ProbabilityLimited",
                "FalseAlarmLimited",
                "AccuracyLimited",
                "FreshnessLimited",
                "CoverageLimited",
                "CapacityLimited",
                "SensingFailure",
            ],
            p("alpha_PHY/X_disc", 221),
        ),
        ClassSpec(
            "PHYState",
            [
                "PHYNormal",
                "PHYCommunicationDegraded",
                "PHYSensingDegraded",
                "PHYJointDegraded",
                "PHYRecovery",
                "PHYFailure",
            ],
            p("alpha_PHY/X_disc", 225),
        ),
    ]

    clocks = [
        ClockSpec("c_meas", "age of last channel measurement", "measure_tick?, channel_report!", p("clocks", 283)),
        ClockSpec("c_sig", "duration of signal configuration", "config commands, signal_report!", p("clocks", 285)),
        ClockSpec("c_sense", "sensing state computation age", "child reports, sensing_report!", p("clocks", 287)),
        ClockSpec("c_report", "aggregated PHY report age", "phy_kpi_report!", p("clocks", 289)),
        ClockSpec("c_rec", "beam recovery duration", "enter BeamRecover", p("clocks", 291)),
        ClockSpec("c_ssb", "SSB/beam-search window duration", "enter BeamSearch or ssb_burst_config?", p("clocks", 293)),
        ClockSpec("aos_bs", "local Age of Sensing at BS", "sensing_success!", p("clocks", 295)),
        ClockSpec("aos_ctrl", "Age of Sensing at controller", "controller_report_delivered?", p("clocks", 297)),
        ClockSpec("c_obs", "observer deadline clock", "enter observer wait state", p("clocks", 300)),
    ]

    handshake = [
        "measure_tick",
        "pilot_config",
        "prs_config",
        "ssb_burst_config",
        "waveform_config",
        "payload_sensing_config",
        "beam_cmd",
        "extra_ssb_cmd",
        "handover_assist_cmd",
        "power_cmd",
        "sensing_mode_cmd",
        "recovery_cmd",
        "new_beam_confirmed",
        "mac_report_delivered",
        "controller_report_delivered",
    ]
    broadcast_reports = ["channel_report", "signal_report", "beam_report", "sensing_report", "phy_kpi_report"]
    broadcast_events = [
        "channel_degraded",
        "signal_degraded",
        "beam_misaligned",
        "beam_failure",
        "sensing_degraded",
        "phy_outage",
        "degradation_event",
        "recovery_event",
        "mobility_alert",
        "multipath_alert",
        "blockage_detected",
        "beam_locked",
        "beam_restored",
        "handover_hint",
        "sensing_failure",
        "phy_failure",
        "sensing_success",
        "aos_ctrl_expired",
        "recovery_start",
        "target_detected",
        "contract_violation_ch",
        "contract_violation_sig",
        "contract_violation_bm",
        "contract_violation_sq",
        "contract_violation_ph",
    ]
    channels = [
        *(ChannelSpec(name, "handshake", "environment/MAC/SDN command", p("channels", 319)) for name in handshake),
        *(ChannelSpec(name, "broadcast", "report notification", p("channels", 325)) for name in broadcast_reports),
        *(ChannelSpec(name, "broadcast", "diagnostic/degradation/recovery event", p("channels", 329)) for name in broadcast_events),
    ]

    variables = [
        *(VariableSpec(item.name, f"{item.name}T", item.values[0], "finite alpha_PHY class variable", item.provenance) for item in classes),
        VariableSpec("W", "WaveformT", "W_OFDM", "finite waveform selector; waveform values are not locations", p("A_SIG", 438)),
        VariableSpec("env_scenario", "int[0,3]", "SCENARIO_NORMAL", "bounded environment scenario selector", p("A_ENV", 705)),
        VariableSpec("channel_degraded_flag", "bool", "false", "diagnostic flag", p("reports", 735)),
        VariableSpec("signal_degraded_flag", "bool", "false", "diagnostic flag", p("reports", 737)),
        VariableSpec("beam_degraded_flag", "bool", "false", "diagnostic flag", p("reports", 739)),
        VariableSpec("sensing_degraded_flag", "bool", "false", "observer trigger metadata", p("reports", 741)),
        VariableSpec("sensing_failure_flag", "bool", "false", "observer trigger metadata", p("reports", 743)),
        VariableSpec("degradation_flag", "bool", "false", "aggregate PHY degradation flag", p("reports", 745)),
        VariableSpec("TimingOk", "bool", "true", "environment timing assumption", p("contracts", 253)),
        VariableSpec("ConfigAdmissible", "bool", "true", "MAC/SDN configuration assumption", p("contracts", 255)),
        VariableSpec("BeamCmdAdmissible", "bool", "true", "beam command assumption", p("contracts", 257)),
        VariableSpec("NetDeliveryOk", "bool", "true", "network delivery assumption", p("contracts", 259)),
    ]

    automata = [
        AutomatonSpec(
            name="A_CH",
            initial="ChannelNominal",
            locations=[LocationSpec(name) for name in [
                "MeasurePending",
                "ChannelNominal",
                "InterferenceLimited",
                "MobilityLimited",
                "MultipathLimited",
                "Blockage",
                "Outage",
                "ContractViolation_CH",
            ]],
            assumptions=["measurements refreshed not later than T_meas + J_meas", "class inputs are in declared enum ranges"],
            guarantees=["channel_report! within D_meas", "ChannelClass follows priority prio_CH"],
            provenance=p("A_CH", 377),
        ),
        AutomatonSpec(
            name="A_SIG",
            initial="SignalNominal",
            locations=[LocationSpec(name) for name in [
                "SignalNominal",
                "PilotBasedSensing",
                "PayloadAssistedSensing",
                "SignalReconfiguring",
                "SignalLimited",
                "ContractViolation_SIG",
            ]],
            assumptions=["MAC/SDN provides admissible waveform and pilot configuration"],
            guarantees=["signal_report! within D_sig", "waveform W is a variable, not a location"],
            provenance=p("A_SIG", 444),
        ),
        AutomatonSpec(
            name="A_BM",
            initial="BeamSearch",
            locations=[
                LocationSpec("BeamSearch"),
                LocationSpec("BeamSearchSeen"),
                LocationSpec("BeamTrack"),
                LocationSpec("BeamLock"),
                LocationSpec("BeamPredict"),
                LocationSpec("BeamMisalign"),
                LocationSpec("BeamRecoveryStart"),
                LocationSpec("BeamRecover", "c_rec <= D_BM"),
                LocationSpec("BeamHOAssist"),
                LocationSpec("BeamFailed"),
                LocationSpec("ContractViolation_BM"),
            ],
            assumptions=["beam commands and SSB/PRS configuration are finite and admissible"],
            guarantees=["recovery outcome no later than c_rec == D_BM", "no c_rec > D_BM transition under BeamRecover invariant"],
            provenance=p("A_BM", 487),
        ),
        AutomatonSpec(
            name="A_SQ",
            initial="Idle",
            locations=[LocationSpec(name) for name in [
                "Idle",
                "SensingEvaluating",
                "SensingQoSOk",
                "ProbabilityLimited",
                "FalseAlarmLimited",
                "AccuracyLimited",
                "FreshnessLimited",
                "CoverageLimited",
                "CapacityLimited",
                "SensingFailure",
                "ContractViolation_SQ",
            ]],
            assumptions=["fresh channel_report?, signal_report?, beam_report?"],
            guarantees=["sensing_report! within D_sense", "SensingState follows priority prio_SQ"],
            provenance=p("A_SQ", 585),
        ),
        AutomatonSpec(
            name="A_PH",
            initial="PHYNormal",
            locations=[LocationSpec(name) for name in [
                "PHYNormal",
                "PHYCommunicationDegraded",
                "PHYSensingDegraded",
                "PHYJointDegraded",
                "PHYKpiReporting",
                "PHYRecovery",
                "PHYFailure",
                "ContractViolation_PH",
            ]],
            assumptions=["child reports delivered within D_child", "aos_bs and aos_ctrl reset correctly"],
            guarantees=["phy_kpi_report! within D_report", "only A_PH updates PHYState"],
            provenance=p("A_PH", 667),
        ),
    ]

    env = [
        EnvSpec(
            "ENV_CH",
            "TickWait",
            [LocationSpec("TickWait")],
            [TransitionSpec("TickWait", "TickWait", sync="measure_tick!", assignment="update finite channel/sensing estimator classes")],
            ["bounded nondeterministic measurement ticks", "continuous estimator values are classified before UPPAAL"],
            p("A_ENV", 705),
        ),
        EnvSpec(
            "ENV_TARGET",
            "TargetWait",
            [LocationSpec("TargetWait")],
            [TransitionSpec("TargetWait", "TargetWait", sync="target_detected!", assignment="update PRSClass, BeamErrorClass, BlockageClass")],
            ["target presence and blockage are abstract finite classes"],
            p("A_ENV", 711),
        ),
        EnvSpec(
            "ENV_MAC",
            "ConfigWait",
            [LocationSpec("ConfigWait")],
            [TransitionSpec("ConfigWait", "ConfigWait", sync="pilot_config!", assignment="ConfigAdmissible = true")],
            ["MAC/SDN commands are admissible in closed-system smoke mode"],
            p("A_ENV", 718),
        ),
        EnvSpec(
            "ENV_NET",
            "DeliveryWait",
            [LocationSpec("DeliveryWait")],
            [TransitionSpec("DeliveryWait", "DeliveryWait", sync="controller_report_delivered!", assignment="NetDeliveryOk = true, aos_ctrl = 0")],
            ["report delivery is bounded by network abstraction"],
            p("A_ENV", 724),
        ),
    ]

    observers = [
        ObserverSpec("ObsSenseReport", "sensing_degraded?", ["phy_kpi_report?"], "D_report", "A[] not ObsSenseReport.Violation", p("observers", 820)),
        ObserverSpec("ObsFreshness", "aos_ctrl_expired?", ["sensing_report?"], "D_sense", "A[] not ObsFreshness.Violation", p("observers", 832)),
        ObserverSpec(
            "ObsBeamRecovery",
            "recovery_start?",
            ["beam_restored?", "handover_hint?", "beam_failure?"],
            "D_BM",
            "A[] not ObsBeamRecovery.Violation",
            p("observers", 842),
        ),
    ]

    properties = [
        PropertySpec("deadlock_free", "A[] not deadlock", "safety", "closed A_SYS has no deadlocks", p("properties", 812)),
        PropertySpec("reach_phy_normal", "E<> A_PH.PHYNormal", "reachability", "normal PHY state is reachable", p("properties", 813)),
        PropertySpec("reach_phy_sensing_degraded", "E<> A_PH.PHYSensingDegraded", "reachability", "sensing degradation is reachable", p("properties", 814)),
        PropertySpec("reach_phy_communication_degraded", "E<> A_PH.PHYCommunicationDegraded", "reachability", "communication degradation is reachable", p("properties", 815)),
        PropertySpec("reach_phy_joint_degraded", "E<> A_PH.PHYJointDegraded", "reachability", "joint degradation is reachable", p("properties", 816)),
        PropertySpec("aggregation_consistency", "A[] (A_PH.PHYNormal imply (comm_ok && sensing_qos_ok))", "safety", "normal state implies both aggregate booleans are ok", p("properties", 817)),
        PropertySpec("ch_determinism", "A[] (ch_enabled_count <= 1)", "safety", "channel classifier has at most one enabled result", p("properties", 858)),
        PropertySpec("sq_determinism", "A[] (sq_enabled_count <= 1)", "safety", "sensing classifier has at most one enabled result", p("properties", 859)),
        PropertySpec("bm_recover_invariant", "A[] (A_BM.BeamRecover imply c_rec <= D_BM)", "safety", "beam recovery never exceeds its invariant", p("properties", 854)),
        *(PropertySpec(observer.name, observer.violation_query, "observer", f"{observer.name} does not reach Violation", observer.provenance) for observer in observers),
        PropertySpec("contract_ch", "A[] (ass_ch() imply not A_CH.ContractViolation_CH)", "contract", "A_CH contract violation is absent under assumptions", p("contracts", 877)),
        PropertySpec("contract_sig", "A[] (ass_sig() imply not A_SIG.ContractViolation_SIG)", "contract", "A_SIG contract violation is absent under assumptions", p("contracts", 878)),
        PropertySpec("contract_bm", "A[] (ass_bm() imply not A_BM.ContractViolation_BM)", "contract", "A_BM contract violation is absent under assumptions", p("contracts", 879)),
        PropertySpec("contract_sq", "A[] (ass_sq() imply not A_SQ.ContractViolation_SQ)", "contract", "A_SQ contract violation is absent under assumptions", p("contracts", 880)),
        PropertySpec("contract_ph", "A[] (ass_ph() imply not A_PH.ContractViolation_PH)", "contract", "A_PH contract violation is absent under assumptions", p("contracts", 881)),
    ]

    contracts = [
        ContractSpec("A_CH", ["ass_ch()"], ["gar_ch()"], "ContractViolation_CH", "contract_violation_ch", p("contracts", 263)),
        ContractSpec("A_SIG", ["ass_sig()"], ["gar_sig()"], "ContractViolation_SIG", "contract_violation_sig", p("contracts", 265)),
        ContractSpec("A_BM", ["ass_bm()"], ["gar_bm()"], "ContractViolation_BM", "contract_violation_bm", p("contracts", 267)),
        ContractSpec("A_SQ", ["ass_sq()"], ["gar_sq()"], "ContractViolation_SQ", "contract_violation_sq", p("contracts", 269)),
        ContractSpec("A_PH", ["ass_ph()"], ["gar_ph()"], "ContractViolation_PH", "contract_violation_ph", p("contracts", 271)),
    ]

    return PhyContractModel(
        source_name=SOURCE,
        phy_components=["A_CH", "A_SIG", "A_BM", "A_SQ", "A_PH"],
        env_components=["ENV_CH", "ENV_TARGET", "ENV_MAC", "ENV_NET"],
        classes=classes,
        clocks=clocks,
        channels=channels,
        automata=automata,
        observers=observers,
        properties=properties,
        contracts=contracts,
        variables=variables,
        env=env,
        invariants=[
            "A_PHY = A_CH || A_SIG || A_BM || A_SQ || A_PH",
            "A_SYS = A_PHY || A_ENV",
            "A_ENV = ENV_CH || ENV_TARGET || ENV_MAC || ENV_NET",
            "guards use finite class variables, not continuous PHY metrics",
            "report/event channels are broadcast; command channels are handshake",
            "bounded deadlines are checked by observers",
        ],
        limitations=[
            "base TA model does not prove radio-physical probabilities",
            "base TA model does not optimize Pi_PHY",
            "counterexamples may be physical scenarios or abstraction artifacts",
            "parameter synthesis is out of scope for this MCP layer",
        ],
    )
