"""Reproduce frozen artifacts from their pinned historical context, in isolation."""
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import time

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
RELATIVE = Path('evidence/scalability/family-series-68')
SOURCE = ROOT / RELATIVE
CANDIDATE = 'a51a77e7852aee514bb0217a17d970fcf94cb704'


def generate(out):
    out = Path(out).resolve()
    if not out.is_relative_to(HERE) or out.exists():
        raise ValueError('Fresh output inside Issue scope required')
    started = time.monotonic()
    scratch_parent = HERE / '.venv'
    scratch_parent.mkdir(exist_ok=True)
    pins = json.loads((SOURCE/'inputs.json').read_text())
    paths = set(pins['files']) | {str(RELATIVE/name) for name in ('generate.py','query_schema.py','inputs.json')}
    with tempfile.TemporaryDirectory(prefix='generation-snapshot-', dir=scratch_parent) as scratch:
        root = Path(scratch)
        for name in sorted(paths):
            data = subprocess.check_output(['git','show',CANDIDATE+':'+name],cwd=ROOT)
            expected = pins['files'].get(name)
            if expected and hashlib.sha256(data).hexdigest()!=expected:
                raise ValueError('Candidate Git blob differs from generator pin: '+name)
            if not expected and data!=(ROOT/name).read_bytes():
                raise ValueError('Generator/input manifest drift: '+name)
            target=root/name
            target.parent.mkdir(parents=True,exist_ok=True)
            target.write_bytes(data)
        prepared=time.monotonic()
        command=[sys.executable,'-B',str(root/RELATIVE/'generate.py')]
        result=subprocess.run(command,capture_output=True,timeout=25)
        generated=time.monotonic()
        if result.returncode:
            raise RuntimeError(result.stderr.decode(errors='replace'))
        files={}
        for path in sorted((root/RELATIVE/'generated').rglob('*')):
            if not path.is_file(): continue
            relative=path.relative_to(root/RELATIVE/'generated')
            raw=path.read_bytes()
            if raw!=(SOURCE/'generated'/relative).read_bytes():
                raise ValueError('Generated bytes differ from baseline: '+str(relative))
            target=out/relative
            target.parent.mkdir(parents=True,exist_ok=True)
            target.write_bytes(raw)
            files[str(relative)]=hashlib.sha256(raw).hexdigest()
        return {'candidate_commit':CANDIDATE, 'pinned_source_files':len(paths),
                'files':files, 'count':len(files), 'command':command,
                'snapshot_preparation_seconds':prepared-started,
                'generator_subprocess_seconds':generated-prepared,
                'copy_and_compare_seconds':time.monotonic()-generated,
                'generator_stdout':result.stdout.decode(errors='replace'),
                'measurement_scope':'generator_subprocess_seconds includes Python startup and generation writes; snapshot preparation/copy reported separately'}


if __name__=='__main__':
    print(json.dumps(generate(Path(sys.argv[1])),indent=2))
