"""Reproduce XML/query bytes and check recorded artifacts; static audit only."""
import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT=Path(__file__).resolve().parents[3]
sys.path.insert(0,str(ROOT/'src'))


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('run',type=Path)
    args=parser.parse_args()
    from uppaal_mcp.integrated.generator import generate
    current=generate(ROOT)
    report=json.loads((args.run/'checks.json').read_bytes())
    for command in report['commands']:
        for stream in ('stdout','stderr'):
            raw=(args.run/command[stream+'_path']).read_bytes()
            if hashlib.sha256(raw).hexdigest()!=command[stream+'_sha256']:
                raise ValueError('raw log hash mismatch: '+command['name'])
    expected=json.loads((args.run/'generated/composition.json').read_bytes())
    for name,text in [('model.xml',current.model_xml),('queries.q',current.queries)]:
        if (args.run/'generated'/name).read_bytes()!=text.encode():
            raise ValueError('regenerated bytes differ: '+name)
    for field in ('model_hash','query_hash','generator_hash','implementation_sources','source_hashes'):
        if current.metadata[field]!=expected[field]:raise ValueError('metadata mismatch: '+field)
    print('Reproduced XML/query bytes; implementation/input hashes and all recorded raw-log hashes match. Static audit only.')


if __name__=='__main__':
    main()
